finalproj2/urls.py
from django.conf import settings
from django.contrib import admin

from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
        path('',include('notices.urls')),
         path('',include('users.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('all-students/', views.all_students, name='all_students'),
    path('all-coordinators/', views.all_coordinators, name='all_coordinators'),
    path('register-student/', views.register_student, name='register-student'),
    path('register-coordinator/', views.register_coordinator, name='register-coordinator'),
    path('register-tnpoffice/', views.register_tnpoffice, name='register-tnpoffice'),
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('student-pro1file/<int:student_prn>/', views.student_profile, name='student_profile'),
    path('profile/edit_coordinator/', views.edit_coordinator_profile, name='coordinator_edit'),
    path('profile/edit_tnpoffice/', views.edit_tnpoffice_profile, name='tnpoffice_edit'),
     path('student/delete/<int:pk>/', views.delete_student, name='student_delete'),

    path('profile/', views.profile, name='profile'),
    path('upload-files/<str:student_prn>/', views.student_upload_files, name='upload_files'),
    path('edit_student_profile/<int:student_prn>/', views.edit_student_profile, name='edit_student_profile'),
    path('change_requests/', views.profile_changes_for_coordinator, name='profile_change_requests'),
    path('approve_profile_change/<int:change_id>/', views.approve_profile_change, name='approve_profile_change'),
    path('deny_profile_change/<int:change_id>/', views.deny_profile_change, name='deny_profile_change'),

    path('apply-drive/<int:drive_id>/', views.apply_drive, name='apply_drive'),
    path('application/success/', views.application_success, name='application_success'),
    path('drive/application/exists/', views.drive_application_exists, name='drive_application_exists'),
    path('drive/applied_students/<int:drive_id>/', views.applied_students_for_drive, name='drive_applied_students'),
    path('my_applications/<int:student_prn>/', views.my_applications, name='my_applications'),

    path('apply-activity/<int:activity_id>/', views.apply_activity, name='apply_activity'),
    path('activity/application/exists/', views.activity_application_exists, name='activity_application_exists'),
    path('activity/applied_students/<int:activity_id>/', views.applied_students_for_activity, name='activity_applied_students'),



    path('search/', views.search_students, name='search_students'),

  path('password-reset/', 
         auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), 
         name='password_reset'),
         
    path('password-reset/done/', 
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), 
         name='password_reset_done'),
         
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), 
         name='password_reset_confirm'),
         
    path('reset/done/', 
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), 
         name='password_reset_complete'),
]

users/models.py
from django.db import models
from notices.models import Department,Drive,Activity
from django.forms import ValidationError
from django.contrib.auth.models import AbstractUser





class CustomUser(AbstractUser):

    USER_CHOICES = [
        ('Student', 'Student'),
        ('Coordinator', 'Coordinator'),
        ('TNP-Office', 'TNP-Office'),
    ]
    user_type = models.CharField(max_length=15, choices=USER_CHOICES,default ='Student')
    username = models.CharField(max_length=10,null=True,blank=True)
    # Specify email as the USERNAME_FIELD
    USERNAME_FIELD = 'email'
    
    # Remove email from REQUIRED_FIELDS
    REQUIRED_FIELDS = []
    # Ensure email is marked as unique
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class Student(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,null=True,blank=True)

    Placement_choice = [
        ('On-campus','On-campus'),
        ('Off-campus','Off-campus'),
    ]
    preferences=[
        ('Job','Job'),
        ('Entrepreneurship','Entrepreneurship'),
        ('Higher Studies','Higher Studies')


    ]

    Gap =[
        ('0','0'),
        ('1','1'),
        ('2','2'),

    ]
    Boolean_choices =[
        ('No','No'),
        ('Yes','Yes'),
    ]
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]


    FIRST_NAME = models.CharField(max_length=255)
    MIDDLE_NAME = models.CharField(max_length=255)
    LAST_NAME= models.CharField(max_length=255)
    PRN = models.PositiveIntegerField(unique=True)
    DOB = models.DateField(default='2001-10-02')
    GENDER = models.CharField(max_length=10, choices=GENDER_CHOICES)
    EMAIL = models.EmailField(unique=True)
    PERSONAL_EMAIL = models.EmailField(unique=True)
    AGE = models.PositiveIntegerField()
    MOBILE_NO = models.PositiveIntegerField()
    ALT_Mobile_NO = models.PositiveIntegerField()
    LOCAL_ADDRS = models.CharField(max_length=255)
    PERM_ADDRS = models.CharField(max_length=255)
    Native_Place = models.CharField(max_length=255)
    X_Percentage = models.DecimalField(max_digits=5, decimal_places=2)
    Xth_marksheet = models.FileField(upload_to='documents/10th', null=True, blank=True)
    X_year_of_passing = models.PositiveIntegerField()
    X_board = models.CharField(max_length=255)
    XIIth_marksheet = models.FileField(upload_to='documents/12th', null=True, blank=True)
    XII_Percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    XII_year_of_passing = models.PositiveIntegerField(null=True, blank=True)
    XII_board = models.CharField(max_length=255, null=True, blank=True)
    Diploma_percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    Diploma_Firstyear_marksheet = models.FileField(upload_to='documents/diploma1', null=True, blank=True)    
    Diploma_Secondyear_marksheet = models.FileField(upload_to='documents/diploma2', null=True, blank=True)    
    Diploma_Thirdyear_marksheet = models.FileField(upload_to='documents/diploma3', null=True, blank=True)    
    Diploma_year_of_passing = models.PositiveIntegerField(null=True, blank=True)
    Diploma_college = models.CharField(max_length=255, null=True, blank=True)
    Diploma_branch = models.CharField(max_length=255, null=True, blank=True)
    Admission_Type = models.CharField(max_length=255)
    YEAR_CHOICES = [(str(year), str(year)) for year in range(2020, 2031)]
    Pass_out_Year = models.CharField(max_length=10, choices=YEAR_CHOICES)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    SEM_1_sgpa = models.DecimalField(max_digits=4, decimal_places=2)
    sem1_marksheet = models.FileField(upload_to='documents/Sem1', null=True, blank=True)
    SEM_2_sgpa = models.DecimalField(max_digits=4, decimal_places=2)
    sem2_marksheet = models.FileField(upload_to='documents/Sem2', null=True, blank=True)
    SEM_3_sgpa = models.DecimalField(max_digits=4, decimal_places=2)
    sem3_marksheet = models.FileField(upload_to='images/documents/Sem3', null=True, blank=True)
    SEM_4_sgpa = models.DecimalField(max_digits=4, decimal_places=2)
    sem4_marksheet = models.FileField(upload_to='documents/Sem4', null=True, blank=True)
    SEM_5_sgpa = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    sem5_marksheet = models.FileField(upload_to='documents/Sem5', null=True, blank=True)
    SEM_6_sgpa = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    sem6_marksheet = models.FileField(upload_to='documents/Sem6', null=True, blank=True)
    SEM_7_sgpa = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    sem7_marksheet = models.FileField(upload_to='documents/Sem7', null=True, blank=True)
    SEM_8_sgpa = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    sem8_marksheet = models.FileField(upload_to='documents/Sem8', null=True, blank=True)
    AVG_TILL_SEM_cgpa = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    AVG_TILL_SEM_percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    Live_backlogs = models.CharField(max_length=25,choices=Boolean_choices)
    Dead_backlogs = models.CharField(max_length=25, choices=Boolean_choices)
    Year_gap = models.CharField(max_length=255,choices=Gap)
    Languages = models.CharField(max_length= 100)
    minor_projects =models.CharField(max_length= 200)
    major_projects =models.CharField(max_length= 200)
    Preference_1 = models.CharField(max_length=255,choices=preferences)
    Preference_2 = models.CharField(max_length=255,choices=preferences)
    Preference_3 = models.CharField(max_length=255,choices=preferences)
    Placed = models.CharField(max_length =20,choices= Boolean_choices, null=True, blank=True)
    Placement_type = models.CharField(max_length =20, null=True, blank=True ,choices=Placement_choice)
    Company_name = models.CharField(max_length =20, null=True, blank=True)
    Profile_photo = models.ImageField(upload_to='images/profiles/student', null=True, blank=True)

    def calculate_average_and_percentage(self):
        sem_sgpa_fields = [self.SEM_1_sgpa, self.SEM_2_sgpa, self.SEM_3_sgpa, self.SEM_4_sgpa, self.SEM_5_sgpa, self.SEM_6_sgpa, self.SEM_7_sgpa, self.SEM_8_sgpa]
        valid_sgpa_values = [sgpa for sgpa in sem_sgpa_fields if sgpa is not None]
        
        if valid_sgpa_values:
            avg_cgpa = sum(valid_sgpa_values) / len(valid_sgpa_values)
            self.AVG_TILL_SEM_cgpa = round(avg_cgpa, 2)
            
            max_sgpa = 10  # Assuming 10 is the maximum SGPA
            percentage = (avg_cgpa / max_sgpa) * 100
            self.AVG_TILL_SEM_percentage = round(percentage, 2)

    def clean(self):
        # Check if either XIIth fields or Diploma fields are filled, but not both
        if (
            (self.XII_Percentage is not None or self.XII_year_of_passing is not None or self.XII_board) and
            (self.Diploma_percentage is not None or self.Diploma_year_of_passing is not None or self.Diploma_college or self.Diploma_branch)
        ):
            raise ValidationError("Either fill the XIIth fields or the Diploma fields, but not both.")
    def save(self, *args, **kwargs):
        self.calculate_average_and_percentage()
        super(Student, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.FIRST_NAME} - {self.PRN}"
       
    

from django.db import models

class Coordinator(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,null=True,blank=True)
    C_ID =  models.CharField(max_length = 25,unique=True)
    NAME = models.CharField(max_length=255)
    GENDER = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    PHONE_NO = models.PositiveIntegerField()
    EMAIL = models.EmailField()
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    PERSONAL_EMAIL = models.EmailField()
    INSTITUTE = models.CharField(max_length=255)
    PROFILE_PHOTO = models.ImageField(upload_to='images/profiles/Coordinator',null=True,blank=True)

    def __str__(self):
        return self.NAME
    


from django.db import models

class TNPOffice(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,null=True,blank=True)
    T_ID =  models.CharField(max_length = 25,unique=True)
    NAME = models.CharField(max_length=255)
    PHONE_NO = models.PositiveIntegerField()
    EMAIL = models.EmailField()
    PERSONAL_EMAIL = models.EmailField()
    PROFILE_PHOTO = models.ImageField(upload_to='images/profiles/tnp',null=True,blank=True)

    def __str__(self):
        return self.NAME
    







class DriveApplication(models.Model):
    drive= models.ForeignKey(Drive, on_delete=models.CASCADE)  # Notice the student applied for
    student = models.ForeignKey(Student, on_delete=models.CASCADE)  # Student applying for the notice
    applied_date = models.DateTimeField(auto_now_add=True)  # Date/time the application was submitted
    round1 = models.BooleanField(default=False)  # Round 1 completed or not
    round2 = models.BooleanField(default=False)  # Round 2 completed or not
    round3 = models.BooleanField(default=False)  # Round 3 completed or not
    round4 = models.BooleanField(default=False)  # Round 4 completed or not
    round5 = models.BooleanField(default=False)  # Round 5 completed or not
    selected = models.BooleanField(default=False)  # Whether the student is selected


    class Meta:
        unique_together = (('drive', 'student'),)

    def __str__(self):
        return f"{self.student.PRN} - {self.drive.title}"      
    
class ActivityApplication(models.Model):

users/templates/activity_application_exists.html
{% extends 'main.html' %}

{% block content %}
<div class="exists_container">
       
        <p class ='exists'>You have already applied to this ACTIVITY</p>
        <a href="{% url 'activities' %}" class="exists_button">OK</a>
    </div>
{% endblock content %}

users/templates/coordinator_profile_changes.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Pending Profile Changes</title>

  <style>
    table {
      border-collapse: collapse;
      width: 100%;
      font-family: 'Poppins', sans-serif;
      

    }
    th, td {
      padding: 8px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    tr:hover {background-color: #f2f2f2;}
    th {
      background-color: #f1f1f1;
    }
  </style>
</head>
<body>

  <h1>Pending Profile Changes</h1>

  <table>
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Field Changed</th>
        <th>Before</th>
        <th>After</th>
      </tr>
    </thead>
    <tbody>
      {% for change in profile_changes %}
      <tr>
        <td>{{ change.student.user.username }} - {{ change.student.name }}</td>
        <td>{{ change.field_changed }}</td>
        <td>{{ change.old_value }}</td>
        <td>{{ change.new_value }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</body>
</html>

users/templates/coordinator_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Student Registration</title>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/registration.css' %}">

</head>
<body>
  <div class="container">
    <div class="left-section">
      <div class="upper-left">
        <h1>Central Training & Placement Department</h1>
        <h3>Providing opportunities and preparing for the workforce.</h3>
      </div>
      <div class="lower-left">
        <img src="{% static 'images/image.png' %}">
      </div>
    </div>
    <div class="right-section">
      <div class="reg_container">
        <div class="title-box">
          <h1>Register a Coordinator </h1>
        </div>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in user_form %}
          <div class="reg-form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
          </div>
          {% endfor %}
          {% for field in coordinator_form %}
          <div class="reg-form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
          </div>
          {% endfor %}
          

          <div class="register-btn">
            <button type="submit" class="btn-primary">Register</button>
          </div>
        </form>
       
      </div>


    </div>
    
  </div>

 

<script>
  document.querySelectorAll('.reg-form-group input').forEach(input => {
      input.addEventListener('focus', function() {
          this.nextElementSibling.style.opacity = 1;
      });
      input.addEventListener('blur', function() {
          this.nextElementSibling.style.opacity = 0;
      });
  });

  document.querySelectorAll('.toggle-password').forEach(item => {
      item.addEventListener('click', function() {
          const input = this.previousElementSibling;
          const type = input.getAttribute('type') === 'password' ? 'text' : 'password';
          input.setAttribute('type', type);
          this.classList.toggle('fa-eye-slash');
      });
  });
</script>
</body>
</html>

users/templates/drive_application_exists.html
{% extends 'main.html' %}

{% block content %}
<div class="exists_container">
       
        <p class ='exists'>You have already applied to this DRIVE</p>
        <a href="{% url 'all-drives' %}" class="exists_button">OK</a>
    </div>
{% endblock  %}

users/templates/edit_profile_photo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Profile Photo</title>
</head>
<body>
    <h1>Edit Profile Photo</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

users/templates/studentProfile.html
{% extends 'main.html' %}
{% block content %}
{% load static %}

<div class="profileContainer">

  <!-- Student Profile -->
  <div class="student-profile">

    <div class="personalDetails">
      {% if request.user.user_type == 'Student' and has_pending_requests %}
      <div class="alert alert-danger mt-4" role="alert" style="padding: 20px; color: white; background-color: red; font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; font-size: 16px; font-weight: bold;">
        Your request for changes in profile has been sent to the designated coordinator.
      </div>
      {% endif %}

      <div class="pr-card">
        <div class="pr-card-header">
          {% if student.Profile_photo %}
          <img class="profile_img" src="{{ student.Profile_photo.url }}" alt="Student DP">
          {% else %}
          <img src="{% static 'images/user-default.png' %}" alt="Student DP" />
          {% endif %}
        </div>
        <div class="pr-card-body">
          <p class="mb-0"><strong class="pr-1">NAME:</strong> {{ student.FIRST_NAME }} {{ student.MIDDLE_NAME }} {{ student.LAST_NAME }}</p>
          <p class="mb-0"><strong class="pr-1">PRN:</strong> {{ student.PRN }}</p>
          <p class="mb-0"><strong class="pr-1">Department:</strong> {{ student.department }}</p>
          <p class="mb-0"><strong class="pr-1">DOB:</strong> {{ student.DOB }}</p>
          <p class="mb-0"><strong class="pr-1">Age:</strong> {{ student.AGE }}</p>
          <p class="mb-0"><strong class="pr-1">Gender:</strong> {{ student.get_GENDER_display }}</p>
          <p class="mb-0"><strong class="pr-1">Graduation Year:</strong> {{ student.Pass_out_Year }}</p>
          <p class="mb-0"><strong class="pr-1">Languages Known:</strong> {{ student.Languages }}</p>
          <p class="mb-0"><strong class="pr-1">Major Projects:</strong> {{ student.major_projects }}</p>
          <p class="mb-0"><strong class="pr-1">Minor Projects:</strong> {{ student.minor_projects }}</p>
          <hr>
          <h3>Documents</h3>
          <div class="document">
            <p class="mb-0"><strong class="pr-1">Xth Marksheet:</strong>
              {% if student.Xth_marksheet %}
              <a href="{{ student.Xth_marksheet.url }}" target="_blank">{{ student.Xth_marksheet.name }}</a>
              {% else %}
              <span>No Xth Marksheet available</span>
              {% endif %}
            </p>
          </div>
          {% if student.XIIth_marksheet %}
          <div class="document">
            <p class="mb-0"><strong class="pr-1">XIIth Marksheet:</strong>
            <a href="{{ student.XIIth_marksheet.url }}" target="_blank">{{ student.XIIth_marksheet.name }}</a>
            </p>
          </div>
          {% endif %}
          {% if student.Diploma_Firstyear_marksheet %}
          <div class="document">
            <p class="mb-0"><strong class="pr-1">Diploma First Year Marksheet:</strong>
            <a href="{{ student.Diploma_Firstyear_marksheet.url }}" target="_blank">{{ student.Diploma_Firstyear_marksheet.name }}</a>
            </p>
          </div>
          {% endif %}
          {% if student.sem1_marksheet %}
          <div class="document">
            <p class="mb-0"><strong class="pr-1">SEM 1 Marksheet:</strong>
            <a href="{{ student.sem1_marksheet.url }}" target="_blank">{{ student.sem1_marksheet.name }}</a>
            </p>
          </div>
          {% endif %}
          {% if student.sem2_marksheet %}
          <div class="document">
            <p class="mb-0"><strong class="pr-1">SEM 2 Marksheet:</strong>
            <a href="{{ student.sem2_marksheet.url }}" target="_blank">{{ student.sem2_marksheet.name }}</a>
            </p>
          </div>
          {% endif %}
          {% if student.sem5_marksheet %}
          <div class="document">
            <p class="mb-0"><strong class="pr-1">SEM 5 Marksheet:</strong>
            <a href="{{ student.sem5_marksheet.url }}" target="_blank">{{ student.sem5_marksheet.name }}</a>
            </p>
          </div>
          {% endif %}
          {% if student.sem7_marksheet %}
          <div class="document">
            <p class="mb-0"><strong class="pr-1">SEM 7 Marksheet:</strong>
            <a href="{{ student.sem7_marksheet.url }}" target="_blank">{{ student.sem7_marksheet.name }}</a>
            </p>
          </div>
          {% endif %}
          

        </div>
      </div>
    </div>
    
    <div class="contactDetails">
      <div class="pr-card">
        <div class="pr-card-body">

          <div class="btn-group">
            {% if request.user.is_authenticated and request.user.user_type == 'Student' %}
            <form action="{% url 'edit_student_profile' student_prn=student.PRN %}">
              <button class="edit-link" type="submit">Edit Profile</button>
            </form>
            <form action="{% url 'upload_files' student_prn=student.PRN %}">
              <button class="edit-link" type="submit">Upload Files</button>
            </form>
            {% endif %}
            {% if request.user.is_authenticated and request.user.user_type != 'Student' %}
            <button class="edit-link">
              <a href="{% url 'my_applications' student_prn=student.PRN %}" style="text-decoration: none; color: inherit;">Applications</a>
            </button>
            {% endif %}
          </div>
         

          <h3>Contact Details</h3>

          
          <div class="contact-info">
            <p class="mb-0"><strong class="pr-1">Email:</strong> {{ student.EMAIL }}</p>
            <p class="mb-0"><strong class="pr-1">Personal Email:</strong> {{ student.PERSONAL_EMAIL }}</p>
            <p class="mb-0"><strong class="pr-1">Mobile No.:</strong> {{ student.MOBILE_NO }}</p>
            <p class="mb-0"><strong class="pr-1">Alternate Mobile No.:</strong> {{ student.ALT_Mobile_NO }}</p>
            <p class="mb-0"><strong class="pr-1">Local Address:</strong> {{ student.LOCAL_ADDRS }}</p>
            <p class="mb-0"><strong class="pr-1">Permanent Address:</strong> {{ student.PERM_ADDRS }}</p>
            <p class="mb-0"><strong class="pr-1">Native Place:</strong> {{ student.Native_Place }}</p>
          </div>
        </div>
        <hr>
        <h3 class="mb-0">Pre-College Academics</h3>
        <div class="pr-card-body">
          <div class="pre-college-info">
            <p class="mb-0"><strong class="pr-1">X-Percentage:</strong> {{ student.X_Percentage }}</p>
            <p class="mb-0"><strong class="pr-1">X-Board:</strong> {{ student.X_board }}</p>
            <p class="mb-0"><strong class="pr-1">X-Year of Passing:</strong> {{ student.X_year_of_passing }}</p>
            {% if student.XII_Percentage %}
            <p class="mb-0"><strong class="pr-1">XII-Percentage:</strong> {{ student.XII_Percentage }}</p>
            <p class="mb-0"><strong class="pr-1">XII-Board:</strong> {{ student.XII_board }}</p>
            <p class="mb-0"><strong class="pr-1">XII-Year of Passing:</strong> {{ student.XII_year_of_passing }}</p>
            {% else %}
            <p class="mb-0"><strong class="pr-1">Diploma-College:</strong> {{ student.Diploma_college }}</p>
            <p class="mb-0"><strong class="pr-1">Diploma-Percentage:</strong> {{ student.Diploma_percentage }}</p>
            <p class="mb-0"><strong class="pr-1">Diploma-Branch:</strong> {{ student.Diploma_branch }}</p>
            <p class="mb-0"><strong class="pr-1">Diploma-Year of Passing:</strong> {{ student.Diploma_year_of_passing }}</p>
            {% endif %}
          </div>
        </div>
        <hr>
        <h3>College Academics</h3>
        <div class="pr-card-body">
          <div class="college-academics-info">
            <p class="profile-info-item"><strong class="pr-1">Admission Type:</strong> {{ student.Admission_Type }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-1 SGPA:</strong> {{ student.SEM_1_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-2 SGPA:</strong> {{ student.SEM_2_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-3 SGPA:</strong> {{ student.SEM_3_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-4 SGPA:</strong> {{ student.SEM_4_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-5 SGPA:</strong> {{ student.SEM_5_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-6 SGPA:</strong> {{ student.SEM_6_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-7 SGPA:</strong> {{ student.SEM_7_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Sem-8 SGPA:</strong> {{ student.SEM_8_sgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Average CGPA:</strong> {{ student.AVG_TILL_SEM_cgpa }}</p>
            <p class="profile-info-item"><strong class="pr-1">Average Percentage:</strong> {{ student.AVG_TILL_SEM_percentage }}</p>
            <p class="profile-info-item"><strong class="pr-1">Live-Backlog:</strong> {{ student.Live_backlogs }}</p>
            <p class="profile-info-item"><strong class="pr-1">Dead-Backlog:</strong> {{ student.Dead_backlogs }}</p>
            <p class="profile-info-item"><strong class="pr-1">Year Gap:</strong> {{ student.Year_gap }}</p>
            <p class="profile-info-item"><strong class="pr-1">Preference-1:</strong> {{ student.Preference_1 }}</p>
            <p class="profile-info-item"><strong class="pr-1">Preference-2:</strong> {{ student.Preference_2 }}</p>
            <p class="profile-info-item"><strong class="pr-1">Preference-3:</strong> {{ student.Preference_3 }}</p>
            <p class="profile-info-item"><strong class="pr-1">Placed:</strong> {{ student.Placed }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}